### ISSUE TITLE
Possible to configure F13 as Print Screen for windows?

### ISSUE THREAD

**Issue by NilsRo** [JulianEberius/k811fn#4]
Hi,

I like the small program using to configure my keyboard for my company. Is it possible to add Print Screen for K811 under Windows as it is provided by K810? Would like to use F13 for that...

Cheers,
Nils

**Comment by JulianEberius** [comment]
Sorry, this is out of scope for this project. I wrote this 5 years ago for a very specific use case, and don't have the capacity (and use case) to work on this anymore.
